language: node_js

node_js:
  - stable

## Cache NPM folder and Cypress binary
## to avoid downloading Cypress again and again
cache:
  directories:
    - ~/.npmgst
    - ~/.cache

install:
  # use the new "ci" command for fastest installs on CI
  - npm install -g codecov
  - npm ci

script:
  - npm run test && codecov
