language: node_js

node_js:
  - stable

## Cache NPM folder and Cypress binary
## to avoid downloading Cypress again and again
cache:
  directories:
    - ~/.npmgst
    - ~/.cache

install:
  - npm install -g codecov
  - npm install

jobs:
  include:
    - stage: test
      script:
        - npm run test
        - codecov
    - stage: deploy
      if: branch = master
      before_script: npm run build
      script: npm run semantic-release
